global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using System.Net.Http.Json;
global using TradeXEcommerce.Client;
global using TradeXEcommerce.Client.Services.ImplementationServices;
global using TradeXEcommerce.Client.Services.InterfaceServices;
global using TradeXEcommerce.Shared.DTO;
global using TradeXEcommerce.Shared.Models;
global using Blazored.LocalStorage;